site_name: GremlinEx
site_url: https://github.com/muchimi/JoystickGremlinEx
theme:
  name: material
  features:
      - navigation.tabs
      - navigation.tabs.sticky  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 # Icon for light mode
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4 # Icon for dark mode
        name: Switch to light mode  
plugins:
  - search
  - glightbox
  - autorefs
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
nav:
  - Home: index.md
  - Overview: overview.md
  - Usage: usage.md
  - Containers : containers.md
  - Actions : actions.md
  - Resources: resources.md
  - Scripting: scripting.md
  - AI and DevOps: ktts.md
  - Credits: credits.md